import Link from 'next/link';
import {api,fmtDate} from '../../../lib/api';
import {JsonLd,breadcrumb} from '../../../lib/schema';
import ArticleActions from '../../../components/ArticleActions';
import HistoryWriter from '../../../components/HistoryWriter';

export default async function Article({params}){
 const {slug}=await params; const decodedSlug=decodeURIComponent(slug||'').trim();
 const result=await api('/articles/'+encodeURIComponent(decodedSlug)).catch(()=>null); const a=result?.data;
 if(!a)return <section className="section"><div className="container"><div className="card empty"><h1>খবরটি পাওয়া যায়নি</h1><p className="muted">খবরটি মুছে ফেলা, draft অবস্থায় থাকা অথবা পুরোনো লিংক হতে পারে।</p><Link className="btn" href="/news">সর্বশেষ খবর দেখুন</Link></div></div></section>;
 const base=process.env.NEXT_PUBLIC_SITE_URL; const url=base+'/news/'+encodeURIComponent(a.slug);
 return <><JsonLd data={{'@context':'https://schema.org','@type':'NewsArticle',headline:a.title,datePublished:a.publishedAt,dateModified:a.updatedAt,image:a.featuredImage?[a.featuredImage]:undefined,author:{'@type':'Person',name:a.author?.name||'ChakriOKhobor'}}}/><JsonLd data={breadcrumb([{name:'Home',url:base},{name:'News',url:base+'/news'},{name:a.title,url}])}/>
 <HistoryWriter article={a}/><section className="section"><div className="container detailGrid"><article className="prose"><div className="articleTop"><span className="tag">{a.category||'News'}</span>{a.isBreaking&&<span className="dangerBadge">BREAKING</span>}</div><h1>{a.title}</h1><p className="muted">{fmtDate(a.publishedAt)} · {a.author?.name||'ChakriOKhobor'} · {a.views||0} views</p>{a.featuredImage&&<img className="articleImage" src={a.featuredImage} alt={a.title}/>}<ArticleActions article={a}/>{a.excerpt&&<p className="articleExcerpt"><b>{a.excerpt}</b></p>}<div className="articleBody" dangerouslySetInnerHTML={{__html:a.content||''}}/>{a.youtubeUrl&&youtubeEmbed(a.youtubeUrl)&&<div className="videoBox"><h3>▶ ভিডিও</h3><iframe src={youtubeEmbed(a.youtubeUrl)} title={a.title} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div>}{a.source?.url&&<p>Source: <a href={a.source.url} rel="nofollow noopener">{a.source.name||a.source.url}</a></p>}</article><aside className="card articleAside"><h3>পাঠকের জন্য</h3><p className="muted">খবরটি গুরুত্বপূর্ণ হলে Save করুন। পরে Dashboard থেকে আবার পড়তে পারবেন।</p><Link href="/news" className="btn secondary">আরও খবর →</Link></aside></div></section></>;
}
function youtubeEmbed(url=''){try{const u=new URL(url);let id=u.searchParams.get('v');if(!id&&u.hostname.includes('youtu.be'))id=u.pathname.slice(1);if(!id&&u.pathname.includes('/shorts/'))id=u.pathname.split('/shorts/')[1]?.split('/')[0];return id?`https://www.youtube.com/embed/${id}`:''}catch{return ''}}
export async function generateMetadata({params}){const {slug}=await params;const decodedSlug=decodeURIComponent(slug||'').trim();const a=await api('/articles/'+encodeURIComponent(decodedSlug)).then(x=>x.data).catch(()=>null);return {title:a?.seo?.title||a?.title||'খবর',description:a?.seo?.description||a?.excerpt||'',keywords:a?.seo?.keywords||undefined,alternates:a?.seo?.canonical?{canonical:a.seo.canonical}:undefined,openGraph:{title:a?.seo?.title||a?.title,description:a?.seo?.description||a?.excerpt||'',images:a?.featuredImage?[a.featuredImage]:undefined,type:'article'}}}
