import Link from 'next/link';
import {api,fmtDate} from '../../../lib/api'; import {JsonLd,breadcrumb} from '../../../lib/schema';

export default async function Job({params}){
 const {slug}=await params;
 const result=await api('/jobs/'+encodeURIComponent(slug||'')).catch(()=>null);
 const j=result?.data;
 if(!j)return <section className="section"><div className="container"><div className="card empty notFoundPage"><div className="notFoundIcon">💼</div><h1>Job not found</h1><p className="muted">এই চাকরির পোস্টটি পাওয়া যায়নি অথবা এটি আর প্রকাশিত নেই।</p><Link href="/jobs" className="btn">← সব চাকরি দেখুন</Link></div></div></section>;
 const base=process.env.NEXT_PUBLIC_SITE_URL;
 return <><JsonLd data={{'@context':'https://schema.org','@type':'JobPosting',title:j.title,description:j.description||j.requirements,identifier:{'@type':'PropertyValue',name:j.company,value:j._id},datePosted:j.publishedAt,validThrough:j.applicationDeadline,employmentType:j.employmentType,qualifications:j.qualification,hiringOrganization:{'@type':'Organization',name:j.company},jobLocation:{'@type':'Place',address:{'@type':'PostalAddress',addressLocality:j.location||'Bangladesh',addressCountry:'BD'}},baseSalary:j.salary?.min?{'@type':'MonetaryAmount',currency:j.salary.currency||'BDT',value:{'@type':'QuantitativeValue',minValue:j.salary.min,maxValue:j.salary.max||j.salary.min,unitText:j.salary.period||'MONTH'}}:undefined,applicationContact:j.applicationUrl?{'@type':'ContactPoint',url:j.applicationUrl}:undefined}}/><JsonLd data={breadcrumb([{name:'Home',url:base},{name:'Jobs',url:base+'/jobs'},{name:j.title,url:base+'/jobs/'+j.slug}])}/><section className="section"><div className="container detailGrid"><article className="prose"><span className="tag">{j.category}</span><h1>{j.title}</h1><h3>{j.company}</h3><div className="grid3"><div><b>পদ</b><br/>{j.vacancies||'উল্লেখ নেই'}</div><div><b>বয়স</b><br/>{j.ageLimit||'উল্লেখ নেই'}</div><div><b>শেষ তারিখ</b><br/>{fmtDate(j.applicationDeadline)}</div></div><hr/><h2>যোগ্যতা</h2><p>{j.qualification||'উল্লেখ নেই'}</p><h2>অভিজ্ঞতা</h2><p>{j.experience||'প্রযোজ্য নয়'}</p><h2>বিস্তারিত</h2><p>{j.description||'বিস্তারিত তথ্য দেওয়া হয়নি।'}</p>{j.requirements?.length>0&&<><h2>শর্তসমূহ</h2><ul>{j.requirements.map((x,i)=><li key={i}>{x}</li>)}</ul></>}{j.applicationUrl&&<a className="btn" href={j.applicationUrl} target="_blank" rel="noopener noreferrer nofollow">আবেদন করুন ↗</a>}{j.officialSource&&<p><a href={j.officialSource} target="_blank" rel="nofollow noopener">অফিসিয়াল সোর্স</a></p>}</article><aside className="list"><div className="card"><h3>দরকারি Tools</h3><Link className="btn secondary" href="/tools">সব Tools দেখুন</Link></div><div className="card"><h3>নোট</h3><p className="muted">আবেদনের আগে অফিসিয়াল সার্কুলার যাচাই করুন।</p></div></aside></div></section></>
}

export async function generateMetadata({params}){const {slug}=await params;const j=await api('/jobs/'+encodeURIComponent(slug||'')).then(x=>x.data).catch(()=>null);if(!j)return {title:'Job Not Found | ChakriOKhobor'};return {title:j.seo?.title||j.title,description:j.seo?.description||j.description||''}}
