'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {api,fmtDate} from '../../lib/api';
export default function Dashboard(){
 const [user,setUser]=useState(null),[saved,setSaved]=useState([]),[history,setHistory]=useState([]),[tab,setTab]=useState('overview'),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const r=await api('/auth/me');setUser(r.data);setSaved(JSON.parse(localStorage.getItem('chakri_saved')||'[]'));setHistory(JSON.parse(localStorage.getItem('chakri_history')||'[]'));}catch{location.href='/login'}finally{setLoading(false)}})()},[]);
 const logout=async()=>{try{await api('/auth/logout',{method:'POST'})}catch{} location.href='/'};
 if(loading)return <section className="section"><div className="container"><div className="card loadingCard">Dashboard loading...</div></div></section>; if(!user)return null;
 return <section className="section dashboardPage"><div className="container"><div className="dashHero"><div><span className="eyebrow">MY DASHBOARD</span><h1>স্বাগতম, {user.name} 👋</h1><p>আপনার পছন্দের খবর, saved articles এবং reading history এক জায়গায়।</p></div><div className="avatar">{(user.name||'U').slice(0,1).toUpperCase()}</div></div><div className="dashStats"><Stat i="🔖" l="Saved News" v={saved.length}/><Stat i="🕘" l="Read History" v={history.length}/><Stat i="📰" l="News" v="24/7"/></div><div className="dashboardGrid"><aside className="dashSide"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>🏠 Overview</button><button className={tab==='saved'?'active':''} onClick={()=>setTab('saved')}>🔖 Saved News</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>🕘 Reading History</button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>👤 My Profile</button><button onClick={logout}>🚪 Logout</button></aside><div className="dashContent">{tab==='overview'&&<><div className="card dashWelcome"><div><span className="tag">YOUR SPACE</span><h2>আপনার news workspace</h2><p className="muted">খবর পড়ুন, গুরুত্বপূর্ণ article save করুন এবং পরে সহজে আবার ফিরে আসুন।</p></div><Link href="/news" className="btn">সর্বশেষ খবর →</Link></div><Section title="Saved News" items={saved.slice(0,3)} empty="এখনও কোনো খবর save করেননি।"/><Section title="Recently Read" items={history.slice(0,3)} empty="আপনার reading history এখানে দেখা যাবে।"/></>}{tab==='saved'&&<Section title="Saved News" items={saved} empty="এখনও কোনো খবর save করেননি।"/>}{tab==='history'&&<Section title="Reading History" items={history} empty="এখনও কোনো article পড়া হয়নি।"/>}{tab==='profile'&&<div className="card profilePanel"><span className="tag">PROFILE</span><h2>{user.name}</h2><p><b>Email</b><br/>{user.email}</p><p><b>Account type</b><br/>{user.role||'user'}</p></div>}</div></div></div></section>;
}
function Stat({i,l,v}){return <div className="dashStat"><span>{i}</span><div><small>{l}</small><strong>{v}</strong></div></div>}
function Section({title,items,empty}){return <div className="dashSection"><div className="sectionHead"><h2>{title}</h2>{items.length>3&&<span className="muted">{items.length} items</span>}</div>{!items.length?<div className="card empty">{empty}<br/><Link href="/news" className="btn secondary">খবর দেখুন</Link></div>:<div className="dashArticles">{items.map(a=><Link className="dashArticle" href={`/news/${a.slug}`} key={a._id}><div className="dashThumb">{a.featuredImage?<img src={a.featuredImage} alt=""/>:<span>NEWS</span>}</div><div><span className="tag">{a.category||'News'}</span><h3>{a.title}</h3><small className="muted">{fmtDate(a.publishedAt||a.createdAt)}</small></div></Link>)}</div>}</div>}
